/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistarRouteImport } from './routes/registar'
import { Route as RedefinirRouteImport } from './routes/redefinir'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const RegistarRoute = RegistarRouteImport.update({
  id: '/registar',
  path: '/registar',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirRoute = RedefinirRouteImport.update({
  id: '/redefinir',
  path: '/redefinir',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/redefinir': typeof RedefinirRoute
  '/registar': typeof RegistarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/redefinir': typeof RedefinirRoute
  '/registar': typeof RegistarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/redefinir': typeof RedefinirRoute
  '/registar': typeof RegistarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/recuperar' | '/redefinir' | '/registar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/recuperar' | '/redefinir' | '/registar'
  id: '__root__' | '/' | '/login' | '/recuperar' | '/redefinir' | '/registar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RecuperarRoute: typeof RecuperarRoute
  RedefinirRoute: typeof RedefinirRoute
  RegistarRoute: typeof RegistarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registar': {
      id: '/registar'
      path: '/registar'
      fullPath: '/registar'
      preLoaderRoute: typeof RegistarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir': {
      id: '/redefinir'
      path: '/redefinir'
      fullPath: '/redefinir'
      preLoaderRoute: typeof RedefinirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RecuperarRoute: RecuperarRoute,
  RedefinirRoute: RedefinirRoute,
  RegistarRoute: RegistarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
